# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/lib_nbs/methods/00_preprocessors.ipynb.

# %% auto 0
__all__ = ['get_percept']

# %% ../../nbs/lib_nbs/methods/00_preprocessors.ipynb 1
def get_percept(observation):
    percept = str(observation)
    return(percept)
