project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false
    
format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    linkcolor: "#384C73"
    monobackgroundcolor: "#000000ff"
    page-layout: full

website:
  title: "Projective Simulation"
  site-url: "https://qic-uibk.github.io/PS/"
  description: "Projective Simulation"
  repo-branch: master
  repo-url: "https://github.com/qic-uibk/projective_simulation/"
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:  
    logo: figs/ps_logo.png
    background: "#f7f1e6ff"
    foreground: "#000000ff"
    search: true      
    right:
      - icon: github
        href: "https://github.com/qic-uibk/projectivesimulation/"     



        
  sidebar: 
    foreground: "#000000ff"
    style: floating
    collapse-level: 1
    contents:
      - text: Get started
        href: index.ipynb
      - section: Documentation
        href: lib_nbs/index_docs.ipynb
        contents:
            - lib_nbs/agents/01_core.ipynb            
            - section: ECMs
              contents:
                - lib_nbs/ECMs/01_core.ipynb
                - lib_nbs/ECMs/02_priming.ipynb
            - lib_nbs/envs/01_core.ipynb
      - section: Tutorials
        href: tutorials/index_tutorials.ipynb
        contents:
            - section: Learning PS
              contents: 
                  - tutorials/learning_ps/00_Introduction_to_PS.ipynb
            - section: Applications
              contents:
                  - tutorials/applications/00_optimal_search.ipynb
            - section: Contributing
              contents:
                  - tutorials/contributing/00_contributing.ipynb
      - text: Research
        href: webpage/research.ipynb