"""In this notebook we will guide you through the basics of contributing to the `projective_simulation` library."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/tutorials/contributing/00_contributing.ipynb.

# %% auto 0
__all__ = ['random_func']

# %% ../nbs/tutorials/contributing/00_contributing.ipynb 20
import numpy as np

def random_func(k): return k*np.random.rand()
