# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lib_nbs/methods/02_utils.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/lib_nbs/methods/02_utils.ipynb 1
import numpy as np
def _softmax(beta, x):
        """
        Given an input, calculates the normalized exponential function.
        """
        # rescale exponential to avoid large numbers
        rescale = max(x)
        exp_x = np.exp(beta *(x-rescale))
        # get normalization
        norm = sum(exp_x)
        # calculate normalized exponential
        softmax_x = exp_x/norm

        return softmax_x
