# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/lib_nbs/00_core.ipynb.

# %% auto 0
__all__ = ['random_func']

# %% ../nbs/lib_nbs/00_core.ipynb 5
import numpy as np

def random_func(k): return k*np.random.rand()
